// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class lab4 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void demoCart() {
    driver.get("http://demo.opencart.com//");
    assertThat(driver.getTitle(), is("Your Store"));
    driver.findElement(By.linkText("Mac (1)")).click();
    assertThat(driver.getTitle(), is("Mac"));
    driver.findElement(By.id("input-sort")).click();
    {
      WebElement dropdown = driver.findElement(By.id("input-sort"));
      dropdown.findElement(By.xpath("//option[. = 'Name (A - Z)']")).click();
    }
    driver.findElement(By.cssSelector(".button-group .hidden-xs")).click();
    js.executeScript("window.scrollTo(0,458)");
    driver.findElement(By.name("search")).click();
    driver.findElement(By.name("search")).sendKeys("monitors");
    driver.findElement(By.cssSelector(".fa-search")).click();
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.id("input-search")).sendKeys(" ");
    driver.findElement(By.id("description")).click();
    driver.findElement(By.id("button-search")).click();
  }
}
